version = 1

[[analyzers]]
name = "python"
enabled = true
# You can specify the version of Python if needed
runtime_version = "3.8.10"

[analyzers.meta]
autofix = true  # Automatically fix issues where possible
