name: CodeClimate Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codeclimate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Change to your project's Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install your project dependencies

      - name: Install CodeClimate CLI
        run: |
          curl -L https://github.com/codeclimate/codeclimate/releases/latest/download/codeclimate-linux-amd64 -o codeclimate
          chmod +x codeclimate  # Make it executable
          sudo mv codeclimate /usr/local/bin/  # Move to bin directory

      - name: Verify CodeClimate CLI
        run: |
          file /usr/local/bin/codeclimate  # Check if it's a valid executable
          ls -l /usr/local/bin/codeclimate  # List the details of the file
          head -n 10 /usr/local/bin/codeclimate  # Check the first few lines of the executable for any anomalies

      - name: Run CodeClimate analysis
        env:
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}  # Ensure this secret is set correctly
        run: |
          codeclimate analyze  # Run the analysis
