name: CodeClimate Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codeclimate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Change to your project's Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install your project dependencies

      - name: Install CodeClimate CLI
        run: |
          curl -L -o codeclimate https://github.com/codeclimate/codeclimate/releases/latest/download/codeclimate-linux-amd64
          if [[ "$(file codeclimate)" != *"executable"* ]]; then echo "Downloaded file is not executable"; exit 1; fi
          chmod +x codeclimate  # Make it executable
          sudo mv codeclimate /usr/local/bin/  # Move to bin directory

      - name: Verify CodeClimate CLI
        run: |
          file /usr/local/bin/codeclimate  # Check if it's a valid executable
          ls -l /usr/local/bin/codeclimate  # List the details of the file
          if [ ! -s /usr/local/bin/codeclimate ]; then echo "Downloaded file is empty."; exit 1; fi
          if ! command -v codeclimate &> /dev/null; then echo "CodeClimate CLI not found in PATH"; exit 1; fi

      - name: Run CodeClimate analysis
        env:
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}  # Ensure this secret is set correctly
        run: |
          codeclimate analyze  # Run the analysis
