name: Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  issues: write  # Allows writing comments to issues
  pull_requests: write  # Allows writing comments to pull requests

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        id: flake8
        run: |
          flake8 . --format=json > flake8-report.json || true

      - name: Comment on Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('flake8-report.json', 'utf-8');
            const commentBody = `### flake8 Report\n\`\`\`json\n${report}\n\`\`\``;

            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              body: commentBody,
            });
