name: Test Comment Workflow

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              body: 'This is a test comment!',
            });
