# name: Post flake8 Report

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# permissions:
#   issues: write
#   pull-requests: write  # Corrected to pull-requests (with a hyphen)

# jobs:
#   post-flake8-report:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Install Python and flake8
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.8'

#       - name: Install dependencies
#         run: |
#           pip install flake8
#           flake8 . --output-file=flake8-report.json || true

#       - name: Debug Event Context
#         run: echo "${{ toJson(github.event) }}"

#       - name: Comment on PR with flake8 report
#         uses: actions/github-script@v6
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           script: |
#             const fs = require('fs');
#             const report = fs.readFileSync('flake8-report.json', 'utf-8');
#             const commentBody = `### flake8 Report\n\`\`\`json\n${report}\n\`\`\``;

#             await github.rest.issues.createComment({
#               ...context.repo,
#               issue_number: context.payload.pull_request.number,
#               body: commentBody,
#             });
name: Post flake8 Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  issues: write
  pull-requests: write

jobs:
  post-flake8-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python and flake8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install flake8

      - name: Get changed files
        id: get_changed_files
        run: |
          # Determine the base commit to compare against
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            base_commit="${{ github.event.before }}"
          else
            base_commit="HEAD^"  # Compare against the previous commit
          fi
          
          # Get the list of changed files
          files=$(git diff --name-only $base_commit ${{ github.sha }})
          echo "Changed files: $files"
          echo "::set-output name=files::$files"

      - name: Run flake8 on changed files
        run: |
          if [ -z "${{ steps.get_changed_files.outputs.files }}" ]; then
            echo "No changes detected. Creating an empty flake8 report."
            echo '{}' > flake8-report.json  # Create an empty JSON report
          else
            flake8 ${{ steps.get_changed_files.outputs.files }} --output-file=flake8-report.json || true
            if [ ! -f flake8-report.json ]; then
              echo "No flake8 errors found. Creating an empty report."
              echo '{}' > flake8-report.json  # Create an empty JSON report if no file was created
            fi
          fi

      - name: Debug Event Context
        run: echo "${{ toJson(github.event) }}"

      - name: Comment on PR with flake8 report
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('flake8-report.json', 'utf-8');
            const commentBody = `### flake8 Report\n\`\`\`json\n${report}\n\`\`\``;

            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              body: commentBody,
            });
