name: Reviewdog Code Review for Python

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'  # Replace with your specific version if needed

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: |
          flake8 . --format=default > flake8-report.txt || true  # Don't fail if issues are found

      - name: Run Reviewdog
        uses: reviewdog/action-reviewdog@v0.13.1  # Use the main Reviewdog action
        with:
          tool_name: flake8
          input: flake8-report.txt
          reporter: github-pr-review
          filter_mode: file
          level: warning  # Options: info, warning, error
