name: Reviewdog Code Review for Python

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace with your Python version

      # Install Python dependencies
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      # Run flake8 linter and save output
      - name: Run flake8
        run: |
          flake8 . --format=default > flake8-report.txt || true  # Do not fail the job if issues are found

      # Run Reviewdog with flake8 output
      - name: Run Reviewdog
        uses: reviewdog/action-flake8@v1
        with:
          reporter: github-pr-review
          level: warning  # Options: info, warning, error
          filter_mode: file  # Only show issues in files changed in the pull request
