name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Set SONAR_SCANNER_OPTS to use Java 17
      - name: Set SONAR_SCANNER_OPTS
        run: echo "SONAR_SCANNER_OPTS=-Djava.home=${{ steps.setup_java.outputs.path }}" >> $GITHUB_ENV

      # Step 4: SonarCloud Scan using SonarSource Action
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: |
            -Dsonar.projectKey=Boopathy-senseai_codeguru_development
            -Dsonar.organization=boopathy-senseai
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=.
