name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify Java version
        run: java -version

      - name: Install SonarScanner
        run: |
          # Install dependencies
          sudo apt-get update
          sudo apt-get install -y unzip wget

          # Download and install SonarScanner
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner-cli-4.6.2.2472-linux.zip
          sudo mv sonar-scanner-4.6.2.2472-linux /usr/local/sonar-scanner

          # Add SonarScanner to the PATH for all future steps
          echo "PATH=/usr/local/sonar-scanner/bin:$PATH" >> $GITHUB_ENV

      - name: Verify SonarScanner installation
        run: |
          # Ensure sonar-scanner is in PATH and verify installation
          sonar-scanner -v

      - name: Set JAVA_HOME for SonarScanner
        run: |
          export JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.13-11/x64
          export PATH=$JAVA_HOME/bin:$PATH
          java -version

          # Set SonarScanner options to use Java 17
          export SONAR_SCANNER_OPTS="-Djava.home=$JAVA_HOME"

          # Run SonarScanner for the project
          sonar-scanner \
            -Dsonar.projectKey=Boopathy-senseai_codeguru_development \
            -Dsonar.organization=boopathy-senseai \
            -Dsonar.host.url=https://sonarcloud.io
