name: Build and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Step 3: SonarCloud Scan
      - name: SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: |
            -Dsonar.projectKey=Boopathy-senseai_codeguru_development
            -Dsonar.organization=boopathy-senseai
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=.
            -Dsonar.projectBaseDir=.
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.13-11/x64
          JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.13-11/x64
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
