name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK 17 (use Temurin)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Ensure using Java 17 (Eclipse Temurin)
          
      # Ensure Java version is correct (for debugging)
      - name: Check Java Version
        run: java -version

      # Cache SonarCloud dependencies
      - name: Cache SonarCloud dependencies
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonarcloud-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-sonarcloud-

      # Run SonarCloud Analysis
      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          args: -Dsonar.projectKey=Boopathy-senseai_codeguru_development -Dsonar.organization=boopathy-senseai -Dsonar.host.url=https://sonarcloud.io -Dsonar.sources=.
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.13-11/x64
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
